NUMBER_OF_ITERATIONS = 100

SAFE_ROAD_KEY = "SAFE_ROAD"
SHORTCUT_KEY = "SHORTCUT"

ADVERSE_AGENT_KEY = "Adverso"
NEUTRAL_AGENT_KEY = "Neutral"

AGENT_COUNT_MAP = {
    ADVERSE_AGENT_KEY: 50,
    NEUTRAL_AGENT_KEY: 50
}

AGENT_LEARNING_RATE_RANGE = {
    ADVERSE_AGENT_KEY: (0.5, 0.1),
    NEUTRAL_AGENT_KEY: (0.15, 0.25)
}

FREE_SHORTCUT_COST = 10
SATURATED_SHORTCUT_COST = 85

SAFE_ROAD_COST = 45

SHORTCUT_THRESHOLD = 25
CONGESTION_FACTOR = 1.2

NUMBER_OF_ROUNDS = 100

OPTIMAL_AGENTS_IN_SHORTCUT = 0
OPTIMAL_COST = 0

BETA = 0.3